### PR TITLE
[LOWCAR] fixes compilation error for lowcar

### PR DESCRIPTION
**Pull request by finnisherthefin**
broke in pull request #258, #256, #255

### CODE REVIEW

**Review by benliao1 — APPROVED** [review]
Looks good! Thanks for working on this :)
